#!/bin/sh
set -e

lb config noauto \
    --mode debian \
    --distribution bookworm \
    --architectures amd64 \
    --binary-images iso-hybrid \
    --bootloaders "syslinux,grub-efi" \
    --archive-areas "main contrib non-free non-free-firmware" \
    --apt-indices false \
    --apt-recommends false \
    --memtest none \
    --win32-loader false \
    --iso-application "EVAH OS" \
    --iso-preparer "EVAH Team" \
    --iso-publisher "EVAH OS" \
    --iso-volume "EVAH_LIVE" \
    "${@}"
